<a href="https://colab.research.google.com/github/shady4real/ann/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
#dividing the dataset into input and output of the dataset 
ds = pd.read_csv('Churn_Modelling.csv')
X = ds.iloc[:,3:-1].values
Y = ds.iloc[:,-1].values

In [5]:
#peforming labelencoding for less number of labels in the column of the dataset
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])


In [6]:
#performing onehotencoding for different labels in the dataset
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
#splitting the model for training and testing 
from sklearn.model_selection import train_test_split
X_train, X_test ,Y_train , Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [8]:
#Scaling for improving the accuracy of the model 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [9]:
#creating the ANN using the sequential() class

ann = tf.keras.models.Sequential()



In [10]:
#adding the first layer of the ann 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
#adding the second layer of the ann
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer='adam',loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [14]:
#training the dataset 
ann.fit(X_train,Y_train , batch_size =32 , epochs =100)

Epoch 1/100
235/235 [==============================] - 1s 2ms/step - loss: 0.6009 - accuracy: 0.6925
Epoch 2/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4798 - accuracy: 0.7961
Epoch 3/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4571 - accuracy: 0.7952
Epoch 4/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4405 - accuracy: 0.7973
Epoch 5/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4278 - accuracy: 0.8015
Epoch 6/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4141 - accuracy: 0.8093
Epoch 7/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.8177
Epoch 8/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3885 - accuracy: 0.8260
Epoch 9/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3785 - accuracy: 0.8311
Epoch 10/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3722 - accura

In [26]:
#always should be in 2D array for predicting
print(int(ann.predict(sc.transform([[1,0,0,502,0,42,8,159660,3,1,0,113931]])) > 0.5))

1


In [22]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
